name: barter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  image_picker: ^0.8.4+4
  image_cropper: ^5.0.1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  geolocator: ^9.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/home_logo.png
    - lib/assets/app_icon.png
    - lib/assets/
    - lib/

flutter_icons:
  android: false
  ios: true
  image_path: "lib/assets/app_icon.png"